version: '3.5'

services:
  rabbit:
    container_name: symfony-api-curso-rabbitmq
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./docker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - symfony-api-curso-network

networks:
  symfony-api-curso-network:
    external: true